### PR TITLE
Issue 258 - Validation

### PR DESCRIPTION
**Pull request by mneil**
I've made a lot of progress on this ticket. It's not complete but I'd like some feedback at this point on the direction I've taken. The commits have some info on my thought process but to summarize:

 > Validating on run and add new validation command

 - Made the most sense to just validate on any command (except init)
 - Validate command is really just a stub to run app.Before

I started overloading app, then adding some info to context, and trying to escape the "scaffolding" in the app.Before func but in the end it complicated things and I gained little (less readable, harder to test) except the ability to run mu and *not* have to validate.

 > Using go validator

I've started writing some validations which are helpful but there's some shortcomings still

 - YAML is already coercing types so no need to validate any bool fields
 - Types like EnvProvider are really just lists of strings. These are already validated by YAML strict parsing
 - The min type on length enforces not empty. An empty int defaults to 0 so setting a min=1 makes the field required or validation fails. Custom validation for ranges of int is possible but not sure if it's really that important
 - Regex gets sloppy for checking strings. I made a custom validator that allows empty strings or it needs to match the regex. This is helpful but still has pitfalls like: validating an instance type. Instance type, for example, would be good as a list of strings that are valid but I'm afraid to hardcode the list of valid instance types anywhere for checking. Maybe using the aws sdk here to get a list of types would be helpful? Not sure how far you want to take it. 

I can continue putting in sane constraints but would like to get feedback on this direction before I put more effort towards it.

### CODE REVIEW

**Comment by cplee** [comment]
@mneil is there validation that addresses data added to the yaml file that doesn't map to attributes in the config struct?  e.g. the following ought to fail:

```
service:
  foo: bar
```

**Comment by mneil** [comment]
Yes there is. The unmarshallStrict command https://github.com/stelligent/mu/pull/325/commits/3ccfc33245c8c2c37035bd05f2d2e1290c5dd39a#diff-e9a5d1857907d273a22898fa5dda2276R252 does just that and works great.

**Comment by cplee** [comment]
Awesome!  

> I can continue putting in sane constraints but would like to get feedback on this direction before I put more effort towards it.

Please proceed.  No need to get fancy (like calling AWS SDK for instance types).  Just sane constraints is a great start!

**Comment by mneil** [comment]
I added as much validation as I think I could. My biggest concern is that some of the validation might be too restrictive. For example, several properties were type "string" and I made them into their own type for better validation. 

An example is Service.Protocol went from string to a new type, ServiceProtocol. This type accepts only "HTTPS" and "HTTP" which are the only two valid values for CFN. However, the code previously called ToUpper on the passed value making "http" and "http" also valid. 

I also put max values for validation that were previously coerced. Example: Service.Priority had no restrictions but it's not set to a max value of 50000 - the maximum priority allowed for that value.

**Pull request merged**
