### PR TITLE
Fixing typo in deploy-database policy

### PR DESCRIPTION
**Pull request by joincamp**
https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonrds.html shows the list of Actions available, and rds:RemoveTagsToResource is meant to be rds:RemoveTagsFromResource

### CODE REVIEW

**Review by akuma12 — APPROVED** [review]
Looks good! Can you do us a huge favor and change `rds:ListTagsToResource` to `rds:ListTagsForResource` ? Apparently someone got happy with the copy/paste :)

**Comment by akuma12** [comment]
Awesome, thanks @joincamp! Looks like we need to resolve some cfn-nag errors. I can fix those pretty easily if you don't mind me pushing a commit to your branch?

**Comment by joincamp** [comment]
Thanks Jim! [invitiation incoming](https://github.com/joincamp/mu/invitations). Push away.

Btw, good running into you here.
-- Jon

**Comment by akuma12** [comment]
@joincamp I was surprised to see you pop up! Are you using Mu? Unfortunately development was stalled for a while, but we're trying to get back on track.

I pushed a PR to the main repo that fixes the cfn-nag tests that are failing in Circle, but we're running into an issue with goreleaser not compiling correctly. We're working on fixing that, and as soon as its ready and we get the  develop branch cleaned up, you should be able to pull the changes into your fork and update your PR and things should hopefully work.

**Comment by joincamp** [comment]
I use it for consulting projects. It makes it really nice and quick to stand up all the general infrastructure properly. I hadn't touched it in about a year though, so getting everything working again took a little doing, but overall it's a huge time saver.

**Pull request merged**
